### PR TITLE
Rel 5 7

### PR DESCRIPTION
**Pull request by tadgh**
Bump to HAPI-FHIR 5.7.0

### CODE REVIEW

**Comment by tadgh** [comment]
@jkiddo would appreciate if you could check this over and approve. In the meantime can you file a bug in HAPI-FHIR for that circular dependency you're hitting, and I'll see if I can get it removed.

**Comment by jkiddo** [comment]
@tadgh I was just about to give you a heads up

**Comment by tadgh** [comment]
All good! Feel free to still comment on any issues you might see, happy to revert and resubmit.

**Comment by jkiddo** [comment]
Check the comment at https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/315

**Pull request merged**
