### PR TITLE
Added Normalized Quantity Search Support

### PR DESCRIPTION
**Pull request by frankjtao**

### CODE REVIEW

**Comment by frankjtao** [comment]
How do I re-run the pipeline @IanMMarshall @jamesagnew

**Comment by frankjtao** [comment]
@jvitrifork The changes depend on hapi-fhir repo, how do I re-run the pipeline?

**Review by IanMMarshall — APPROVED** [review]
Approved.

**Review by jamesagnew — APPROVED** [review]
Looks great!

**Pull request merged**
