### PR TITLE
Bump to HAPI 6.8.0

### PR DESCRIPTION
**Pull request by dotasek**
Increments HAPI parent to 6.8.0.

### CODE REVIEW

**Comment by jkiddo** [comment]
@dotasek would a unit test with the use of the support for http://hl7.org/fhir/uv/subscriptions-backport/ be part of the PR?

**Comment by jkiddo** [comment]
...and you might wanna have a look at https://github.com/hapifhir/hapi-fhir/issues/5186 as well

**Comment by dotasek** [comment]
@jkiddo this was intended as a version bump only to ensure that the branch compiles with the HAPI release version, and all existing tests pass.

**Comment by jkiddo** [comment]
The issue I referred to causes runtime exceptions that I dont think should be present in 6.8 (while they are there in previous releases)

**Comment by dotasek** [comment]
@jkiddo Is this related to https://github.com/hapifhir/hapi-fhir/pull/5190?

**Comment by jkiddo** [comment]
Yes

**Comment by dotasek** [comment]
Will Gary's PR fix this issue?

**Comment by jkiddo** [comment]
Yes

**Comment by dotasek** [comment]
Auto-merge has been enabled on https://github.com/hapifhir/hapi-fhir/pull/5190. Once it's merged in, unless there's another blocking issue, I believe this PR should be merged as well.

**Comment by dotasek** [comment]
https://github.com/hapifhir/hapi-fhir/pull/5190 is merged.

**Review by michaelabuckley — APPROVED** [review]

**Pull request merged**
