### PR TITLE
Feature/dynamic content

### PR DESCRIPTION
**Pull request by jkiddo**
Refined how custom web apps can be hosted and how the standard templates can be changed using simple overwrites (FYI @costateixeira )

### CODE REVIEW

**Comment by jkiddo** [comment]
@costateixeira you probably need to talk to some Smile guys if you want this into the starter project.

**Comment by joofio** [comment]
Hi,
such a feature would be super welcomed to several projects!

**Comment by costateixeira** [comment]
@dotasek probably you are expecting some testing behind this. I have tested and this works, but you may require some test case - is that true?
@jkiddo is this currently going to set the Flintstones image as the default logo? I would hope not.

**Comment by jkiddo** [comment]
@costateixeira lets cook something different up in the next couple of days then

**Comment by jkiddo** [comment]
@costateixeira I've fixed the defaults now to something more proper. Please let me know what else is on your mind.

**Comment by jkiddo** [comment]
@dotasek & @costateixeira would you guys exchange thoughts on where this needs to head - down the drain or into master?

**Comment by costateixeira** [comment]
I'd say master.
We already had some discussion on how to test this, right?

**Comment by joofio** [comment]
i can help with testing.

**Comment by jkiddo** [comment]
Sounds good to me - I would just like to not keep maintaining a separate branch but rather get it merged.

**Review by patrick-werner — APPROVED** [review]
looking great. I think the PR needs a better description as not only dynamic web_content support was added, but also operations for IG (un)installation.

**Comment by jkiddo** [comment]
> looking great. I think the PR needs a better description as not only dynamic web_content support was added, but also operations for IG (un)installation.

IIRC then that has already be introduced. I'd say that this PR maybe did some unintended formatting around it.

**Pull request merged**
