### PR TITLE
Ips jpa connectathon 2023

### PR DESCRIPTION
**Pull request by psavva**
Work done for the 2023 January Connectathon in Las Vegas.

The following PR will migrate the cql configuration to Cr (Clinical Reasoning) 
Instantiates the IpsOperatorProvider and the beans required for enabling IPS

### CODE REVIEW

**Comment by psavva** [comment]
@jkiddo  @jamesagnew  @jddamore 

The IPS implementation in the Starter is ready.
Configuration item added "ips_enabled" which you can either enable or disable the feature.

**Comment by jkiddo** [comment]
```
[ERROR] Failed to execute goal on project hapi-fhir-jpaserver-starter: Could not resolve dependencies for project ca.uhn.hapi.fhir:hapi-fhir-jpaserver-starter:war:6.3.7-SNAPSHOT: Could not find artifact ca.uhn.hapi.fhir:hapi-fhir-jpaserver-ips:jar:6.3.7-SNAPSHOT in oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```

**Comment by jamesagnew** [comment]
Sorry @jkiddo - I still need to finish documentation on the HAPI FHIR PR and get it through and pushed to maven before this one will build.

I'll do that and ping you on this ticket when that has happened, should be a couple days but not longer.

**Comment by jkiddo** [comment]
No problemo - looking forward to it!

**Comment by psavva** [comment]
@jamesagnew Do you need me to make any changes to this PR, or are we ok?

**Comment by jamesagnew** [comment]
@psavva - The [IPS hapi-fhir ticket](https://github.com/hapifhir/hapi-fhir/pull/4438) is reviewed and approved, just waiting for one internal ticket to pass review before I can merge. Should happen later today, at which point I'll push a new snapshot and this ticket should build cleanly and be ready for review.

**Comment by psavva** [comment]
@jkiddo   Please review, and merge when ready :)
Please let me know if you require any further changes

**Comment by jkiddo** [comment]
LGTM

**Review by jkiddo — APPROVED** [review]

**Pull request merged**
