### PR TITLE
Spring-Security

### PR DESCRIPTION
**Pull request by nitish-diops**

### CODE REVIEW

**Comment by nitish-diops** [comment]
@dickson-diops please review Code

**Comment by XcrigX** [comment]
@nitish-diops - Looks like this PR was submitted against the main project rather than your fork.

**Comment by KevinDougan** [comment]
Hello @nitish-diops and @dickson-diops,

I don't believe it is appropriate to add Spring Security to the **hapi-fhir-jpaserver-starter** project.
The intention of this project is to be a simple wrapper around the **hapi-fhir** project, so that you can get up & running as quickly as possible.
Note the following in the **README**:
https://github.com/hapifhir/hapi-fhir-jpaserver-starter?tab=readme-ov-file#hapi-fhir-starter-project
where it says:
"1. The service comes with no security implementation. See how it can be done [here](https://hapifhir.io/hapi-fhir/docs/security/introduction.html)"

Therefore, I think you should probably **CANCEL** this PR.

Thanks,
Kevin

**Comment by nitish-diops** [comment]
Hello Kevin Dougan,

I hope this message finds you well. I would like to sincerely apologize for mistakenly submitting a pull request to the main branch instead of the appropriate forked repository.
I understand the importance of adhering to our workflow processes and will ensure that all future submissions are directed to the correct repository. Thank you for your understanding, and I appreciate your support as I work to rectify this matter.

Thanks,
Nitish Kumar

________________________________

**Pull request closed without merging**
