### PR TITLE
Sample data generator with Synthea

### PR DESCRIPTION
**Pull request by jjcosare**
Added synthea script for automation on adding data into fhir server, this would be useful in testing out the starter project with some dummy data

### CODE REVIEW

**Comment by patrick-werner** [comment]
i like the idea in general, but i personally think this should be part of the synthea distribution and not part of the jpaserver-starter.

**Comment by seanmcilvenna** [comment]
@patrick-werner I agree. However, I don't want to outright reject the PR. Will leave that to @jamesagnew

**Comment by seanmcilvenna** [comment]
@jjcosare there are conflicting files... I'm still leaving @jamesagnew to review this, but thought I would point out that it definitely won't be merged until at least the conflicts are resolved :)

**Review by psavva — COMMENTED** [review]
I would recommend a widows batch file to be included with would be on par with the file bash file clean_generate_install_fhir.sh

**Comment by jkiddo** [comment]
Closed due to inactivity

**Pull request closed without merging**
