### PR TITLE
Upgrade to springboot 3.0.1.

### PR DESCRIPTION
**Pull request by lukedegruchy**

### CODE REVIEW

**Comment by XcrigX** [comment]
I'm wondering if this wouldn't be safer to do in the base HAPI project? As in - have the base HAPI project import the SpringBoot BOM, and rely on the curated versioning in it so that everything is tested with the updated Spring versions. It seems dangerous to mix-n-match core spring and spring boot versions.

**Comment by jkiddo** [comment]
We should probably read a bit into https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide

**Comment by jkiddo** [comment]
First requirement is to have the spring core dependency in hapi base bumped to 6

**Comment by jkiddo** [comment]
@lukedegruchy looks like https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/618 superseeds this PR - correct?

**Comment by lukedegruchy** [comment]
> @lukedegruchy looks like #618 superseeds this PR - correct?

@jkiddo This MR is really and I'll close it momentarily.

If I were to speculate, I would say James' intention in his PR is to pull in hapi-fhir's springboot version, but I can't say 100%.

Please perform your due diligence when testing the other PR.

**Comment by lukedegruchy** [comment]
Closing since this PR is obsolete.

**Pull request closed without merging**
