### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by jvitrifork**
Proposal to go distroless as default

### CODE REVIEW

**Comment by jvitrifork** [comment]
See https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/137 for comments

**Comment by jvitrifork** [comment]
@jamesagnew / @seanmcilvenna are we gonna proceed with this?

**Comment by seanmcilvenna** [comment]
Generally, I'm fine with it...
But, I don't know how `CMD ["main.war"]` will work? Maybe it's just that I'm not familiar _enough_ with distroless images. Does a distroless java image know to run main.war from the cli in tomcat???

**Comment by jvitrifork** [comment]
if its a repackaged spring boot application, as it is in this case, then yes. I suggest you give it a spin, try to run it if you want to see it for yourself

**Comment by jvitrifork** [comment]
So are we proceeding with this?

**Comment by jamesagnew** [comment]
I am not really clear on what the actual benefit is to this.. Smaller image size presumably?

We often need to ask people to take heap dumps and thread dumps, do those tools still work in this base image? Is anything else lost by changing the base image?

**Comment by jvitrifork** [comment]
In that case, I suggest to default to the use of https://github.com/GoogleContainerTools/distroless#debug-images

**Comment by jamesagnew** [comment]
I still don't get why this is better though. What do we gain by using this image? And do we know for sure that the JDK in the suggested image includes `jstack` and `jmap` tools?

**Comment by jvitrifork** [comment]
I had no idea that there were users of this docker image that also needed to step into the container to execute eg. `jstack`. I would suspect those users would just use a local installation of tomcat or alike

**Comment by jvitrifork** [comment]
The idea with distroless was to downsize and examplify a setup as close to production as possible, without being totally fit for production.

**Comment by jamesagnew** [comment]
Well, I mean I'll put it like this: there are people of widely different levels of knowledge, experience, etc. who use HAPI FHIR. The reason I raise this kind of thing so often is that we do get toooons of support questions/emails/posts from people and it's hard (if not impossible) to keep up.

If someone is a beginner and reports a deadlock and I can point them to how to grab a thread dump so that we can help figure out what they are seeing, that's a good thing. I'd like to avoid having to tell them that they will need to rearchitect to not use docker.

I dunno, this is a hard balance to get right and I never feel like we get it quite right. I don't want hapi to just always strive to be the lowest common denomionator since beginners are generally not the ones building big production systems that HAPI was designed for in the first place, but I do also think that the types of people who need to squeeze every megabyte out of the docker image size for their deployment architecture are likely the ones who will be creating their own dockerfile anyway.

So with all of that said, what is your recommendation?

**Comment by jvitrifork** [comment]
I get it - it's really hard to address such different needs and put it down in a box where everybody are satisfied. It more or less sounds like all options should be availble. If the user spectrum is as broad as you describe, it actually sounds like using docker way beyond what is needed here - besides the folks that just wants a FHIR server running for demo/development purposes without going into the details of what actually resides in docker. On the other hand - if people are actually skilled enough to step into a running container and execute black wizardry then distroless is probably not the right way to go. With that said, I guess we could just provide the distroless Docker recipe as part of the readme as an example and not have it as a part of the actual default docker setup.

**Comment by jamesagnew** [comment]
Makes sense

**Comment by jvitrifork** [comment]
Superseeded by https://github.com/hapifhir/hapi-fhir-jpaserver-starter/pull/160

**Pull request closed without merging**
