### PR TITLE
Support for optional, external configuration file

### PR DESCRIPTION
**Pull request by xluandc**
Allow optional, external configurations to override the entries in hapi.properties.

Such configurations can be specified in a properties file outside of the war (or
webapps/hapi-fhir-jpaserver) and the server may be instructed to load the configuration using
  -Dhapi.properties=<path-of-external-configuration-file>
This is helpful in at least two use cases:
1. Deploying multiple instances with different configurations (e.g., different databases)
2. Future upgrade - just update the war without the need to change hapi.properties after update.

### CODE REVIEW

**Comment by seanmcilvenna** [comment]
@xluandc Please update the pull request to resolve the merge conflicts. After you have done that, I'll re-review and merge. Thanks

**Comment by xluandc** [comment]
Merge conflicts have been resolved, thanks!

**Comment by xluandc** [comment]
Sorry accidentally clicked the wrong button, reopened.

**Comment by seanmcilvenna** [comment]
Looks good! Thanks!

**Pull request merged**
