### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by jkiddo**

### CODE REVIEW

**Comment by jkiddo** [comment]
if approved - can we then do a release of it as well?

**Comment by adamzkover** [comment]
+1, we would also welcome this feature. Tested locally - works on my computer.

**Comment by jkiddo** [comment]
@KevinDougan-SmileCDR since accepted the merge will you then make a 7.0.2 release?

**Comment by KevinDougan-SmileCDR** [comment]
@jkiddo   @adamzkover 

I just published Release v7.0.2 it now:

https://github.com/hapifhir/hapi-fhir-jpaserver-starter/releases/tag/image%2Fv7.0.2

**Pull request merged**
