### PR TITLE
Feat/ig install

### PR DESCRIPTION
**Pull request by jkiddo**

### CODE REVIEW

**Comment by jkiddo** [comment]
This is a feature requested by @costateixeira for speeding up the process of having an IG and make it usable without having to reboot the server instance. It is disabled by default.

**Comment by dotasek** [comment]
Is there a way to automatically test this feature?

**Comment by costateixeira** [comment]
Should be possible.
 upload a package.tgz - can be from any of our IGs (e.g. sample IG), do the
POST and then do the GET a conformance resource e.g.
StructureDefinition/myObservation

Not sure if we have to account for cache refresh etc.

**Review by dotasek — APPROVED** [review]
See testing procedure in comments.

**Comment by costateixeira** [comment]
Sounds like "pass", right?

**Pull request merged**
