### PR TITLE
add <attachClasses>true</attachClasses> to  maven-war-plugin configuration

### PR DESCRIPTION
**Pull request by jschneid-nmdp**
Please consider adding a classes jar artifact, as illustrated here.

The classes jar can be a useful dependency for a project that implements a hapi-fhir server with no test overlay.  It also enables clean separation between code maintained here and specialized code that isn't tightly bound to this project (e.g. custom AuthorizationInterceptor, custom Dockerfile, etc.).

### CODE REVIEW

**Comment by jvitrifork** [comment]
Why would you in the first place depend on the starter project?

**Comment by jschneid-nmdp** [comment]
I'd prefer to bring it in as a dependency, rather than copy/paste the code.

**Comment by jvitrifork** [comment]
@jschneid-nmdp if this is something that you intend to actually use for other demo purposes I see your point. Let me know if that is your intention and I'll approve the PR

**Comment by jschneid-nmdp** [comment]
Yeah, I'd like to use it for non-demo purposes.

**Comment by jvitrifork** [comment]
Okay - hmmm ... I consider this a project that is more of a demo purpose of what can be achieved combining HAPI and Spring Boot. I wouldn't say that it has sufficient test coverage but I see the value in not copying a lot of code

**Comment by jvitrifork** [comment]
If it bears value to others that this is approved, then I'll approve it.

**Comment by jschneid-nmdp** [comment]
Thanks!

**Comment by patrick-werner** [comment]
Thanks (also using this as a base for non-demo purposes)

**Comment by jschneid-nmdp** [comment]
The following example pom to repackage *.class files from the released war artifact is a potential short-term workaround.

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>my-groupId</groupId>
    <artifactId>my-artifactId</artifactId>
    <packaging>jar</packaging>
    <name>jpaserver starter jar</name>

    <dependencies>
        <!-- inherit hapi-fhir-jpaserver-starter dependencies -->
        <dependency>
            <groupId>ca.uhn.hapi.fhir</groupId>
            <artifactId>hapi-fhir-jpaserver-starter</artifactId>
            <type>pom</type>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <!-- unpack war file -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <configuration>
                    <excludeTransitive>true</excludeTransitive>
                    <outputDirectory>${project.build.directory}/dependency</outputDirectory>
                    <includes>WEB-INF/classes/**</includes>
                    <artifactItems>
                        <artifactItem>
                            <groupId>ca.uhn.hapi.fhir</groupId>
                            <artifactId>hapi-fhir-jpaserver-starter</artifactId>
                            <type>war</type>
                        </artifactItem>
                    </artifactItems>
                </configuration>
                <executions>
                    <execution>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <!-- repackage WEB-INF/classes/**/*.class files into new jar -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <classesDirectory>${project.build.directory}/dependency/WEB-INF/classes</classesDirectory>
                    <includes>
                        <include>**/*.class</include>
                    </includes>
                </configuration>
            </plugin>

        </plugins>
    </build>

</project>
```

**Pull request merged**
