### PR TITLE
Added instructions about removing Hibernate dialect

### PR DESCRIPTION
**Pull request by MacL3an**
To fix the problem raised in [this](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/issues/318) issue.

### CODE REVIEW

**Comment by jkiddo** [comment]
@MacL3an your suggested change contradicts https://github.com/hapifhir/hapi-fhir-jpaserver-starter/blob/deefd595dd0189efe9f1945a7aac7757a04f3cba/src/main/resources/application.yaml#L23

**Comment by patrick-werner** [comment]
I think this can be closed, application.yaml has documentation on when to add dialect, and when not to.
@MacL3an @jkiddo

**Comment by MacL3an** [comment]
> #Hibernate dialect is automatically detected except Postgres and H2. 

Yes, but since the default value in the application.yaml file seems to be H2, I thought it would be nice a courtesy to users to remind them that they have to manually remove this default?

> I think this can be closed, application.yaml has documentation on when to add dialect, and when not to.

There are some notes, but since the Readme actually has a explicit section on what to do when running MySQL, why not make that section complete? Right now it only contains some of the steps needed to run MySQL, not of all of them. Instead people have to read through the application.yaml file as well, understand it and make changes that are not mentioned in the readme before they can run HAPI with MySQL.

**Comment by jkiddo** [comment]
@MacL3an I guess you have a point there

**Review by patrick-werner — APPROVED** [review]

**Comment by patrick-werner** [comment]
> @MacL3an I guess you have a point there

i agree

**Pull request merged**
