### PR TITLE
Added Helm chart for installing the server on Kubernetes

### LINKED ISSUE #206: Helm chart for installing on Kubernetes
I've recently created a Helm chart to make it easier to install the HAPI FHIR server on Kubernetes:

https://github.com/chgl/charts/tree/master/charts/hapi-fhir-jpaserver

My main question is if there's interest in including this chart in the `hapi-fhir-jpaserver-starter` repo? Over at https://github.com/chgl/charts I am using https://github.com/helm/chart-releaser to host Helm charts using GitHub pages. Something similar could be set-up in this repo, or a dedicated `hapifhir/charts` repo could be created. 

Of course if there are no plans to officially support any Kubernetes/Helm installation, then that's perfectly fine too!

### PR DESCRIPTION
**Pull request by chgl**
Closes #206 

This adds a Helm chart for installing the HAPI FHIR server on Kubernetes. This also adds GitHub workflows to lint any changes to the chart and integration-test the installation using KinD (https://github.com/kubernetes-sigs/kind) and Helm chart testing (https://github.com/helm/chart-testing).

The chart currently uses a privately built variant of the HAPI FHIR container image (https://github.com/users/chgl/packages/container/package/hapifhir%2Fhapi-fhir-jpaserver-starter, build via `docker build -t ghcr.io/chgl/hapifhir/hapi-fhir-jpaserver-starter:v5.3.0-distroless --target=release-distroless .`), but as soon as a new image release (see #217) is created I'll update the chart (or we can keep this PR open until then).

It also adds GitHub actions to turn this repo into a Helm chart repository and store the chart artifacts using GitHub Pages (https://github.com/helm/chart-releaser). ⚠This requires enabling GitHub pages for this repository, by first creating a `gh-pages` branch and then enabling pages in the settings (https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

### CODE REVIEW

**Comment by jkiddo** [comment]
I finally have some time to get back to the project now ... @jamesagnew / @patrick-werner / @seanmcilvenna  have you activated the Github pages? I do not have sufficient access to do that

**Comment by jvitrifork** [comment]
@jamesagnew

**Comment by jvitrifork** [comment]
I'm gonna merge this and hope that @jamesagnew eventually turns on gh-pages

**Comment by chgl** [comment]
Thank you @jvitrifork ! I'll have to create a new PR to update some things in the chart (like the most recent hapi fhir image version) anyways, so no rush.

**Pull request merged**
